# Base directories
base_dirs:
  data: "./data"  # Changed to use the actual data directory
  meta: "./meta"
  results: "./results/"
  temp: "/tmp"

# Data synchronization settings
data_sync:
  # source_path: "/mnt/dsdd/datasets/bcss/bcss-kaggle/BCSS_512/"
  destination_path: "${base_dirs.data}/"

dataset:
  # Source directories - these are now tissue type specific directories
  source_dirs:
    tissue_dirs:
      - "aSMA_SmoothMuscle"
      - "CD235a_RBC"
      - "CD3CD20_Lymphocyte"
      - "CD45RB_Leukocyte"
      - "ERG_Endothelium"
      - "MIST1_PlasmaCell"
      - "MNDA_MyeloidCell"
      - "panCK_Epithelium"
    he_suffix: "_HE.png"  # Suffix for histology images
    mask_suffix: "_mask.png"  # Suffix for mask images
  
  # Output directories - keep these the same for compatibility with other scripts
  output_dirs:
    train_source: ${base_dirs.data}/train/source-original/
    train_target: ${base_dirs.data}/train/target-original/
    val_source: ${base_dirs.data}/val/source-original/
    val_target: ${base_dirs.data}/val/target-original/
  
  # Split configuration
  split:
    train_percentage: 90
    # val_percentage will be calculated as (100 - train_percentage)

# Temporary file paths
temp_files:
  all_shuffled: ${base_dirs.temp}/all_shuffled_images.txt
  train_list: ${base_dirs.temp}/train_images.txt
  val_list: ${base_dirs.temp}/val_images.txt

# Cleanup configuration
cleanup:
  remove_old_dirs: false

paths:
  labels_tsv: "${base_dirs.meta}/class_codes.tsv"
  labels_detailed_tsv: "${base_dirs.meta}/class_codes_detailed.tsv"
  
  # Train paths
  train_mask_dir: "${base_dirs.data}/train/source-original"
  train_target_dir: "${base_dirs.data}/train/target-original"
  train_plain_mask_dir: "${base_dirs.data}/train/source-original"  # Changed to use original folder
  train_colored_mask_dir: "${base_dirs.data}/train/source"
  train_prompt_output_path: "${base_dirs.data}/train/prompt.json"
  
  # Validation paths
  val_mask_dir: "${base_dirs.data}/val/source-original"
  val_target_dir: "${base_dirs.data}/val/target-original"
  val_plain_mask_dir: "${base_dirs.data}/val/source-original"  # Changed to use original folder
  val_colored_mask_dir: "${base_dirs.data}/val/source"
  val_prompt_output_path: "${base_dirs.data}/val/prompt.json"
  
  results_dir: "${base_dirs.results}"

files:
  output_file: "pixel_class_percentages.csv"
  # Class mapper - simplified for 5-classes only
  mapper: "${base_dirs.meta}/mapper_5.yaml"

settings:
  mask_file_extension: "png"
  num_classes: 9
  # Color map for 9 classes (0-8)
  colors: [
    "#000000", # outside_roi (Black)
    "#FF0000", # CD235a_RBC (Red)
    "#00FF00", # ERG_Endothelium (Green)
    "#0000FF", # MNDA_MyeloidCell (Blue)
    "#FFFF00", # CD3CD20_Lymphocyte (Yellow)
    "#FF00FF", # aSMA_SmoothMuscle (Magenta)
    "#00FFFF", # CD45RB_Leukocyte (Cyan)
    "#FFA500", # MIST1_PlasmaCell (Orange)
    "#8A2BE2"  # panCK_Epithelium (Blue Violet)
  ]
  # Multiprocessing settings
  thread_multiplier: 2
  # Prompt generation settings
  empty_mask_threshold: 0.98
  min_class_percentage: 1.0
  prompt_template: "pathology image: {class_descriptions}"